Vagrant.configure("2") do |config|

  # BOX padrão das máquinas (Ubuntu 22.04 LTS)
  config.vm.box = "ubuntu/jammy64"

  # ---------------------------
  # VM 1 – Servidor (SERVIDOR PRINCIPAL)
  # ---------------------------
  config.vm.define "srv" do |srv|
    srv.vm.hostname = "srv"
    srv.vm.network "private_network", ip: "192.168.56.10"

    # Recursos
    srv.vm.provider "virtualbox" do |vb|
      vb.name = "Servidor-Principal"
      vb.memory = 2048
      vb.cpus = 2
    end

    # Provisionamento automático
    srv.vm.provision "shell", path: "provision/provision_srv_main.sh", privileged: true
  end

  # ---------------------------
  # VM 2 – Cliente/Teste (CLIENTE)
  # ---------------------------
  config.vm.define "cli" do |cli|
    cli.vm.hostname = "cli"
    cli.vm.network "private_network", ip: "192.168.56.20"

    # Recursos
    cli.vm.provider "virtualbox" do |vb|
      vb.name = "Cliente-Teste"
      vb.memory = 1024
      vb.cpus = 1
    end

    # Provisionamento automático
    cli.vm.provision "shell", path: "provision/provision_cli.sh", privileged: true
  end

end